app/Http/routes.php
<?php
use App\Categoria_Servicio as Categoria;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::get('/', function () {

	$categorias=Categoria::mostrarNav()->get();

    return view('welcome',compact('categorias'));

});

Route::get('usuario/datos','UsuarioController@datosUsuarios')
															->name('usuario.datos');

Route::get('usuario/datos/edit','UsuarioController@datosUsuariosEdit')
																->name('usuario.datos.edit');

Route::put('usuario//datos/edit','UsuarioController@datosUsuariosUpdate')
																->name('usuario.datos.update');															

Route::resource('usuario','UsuarioController');

Route::resource('usuario/perfil','PerfilUsuarioController',['names' => 
																		[
																		 'create'  => 'usuario.perfil.create',
																		 'edit'    => 'usuario.perfil.edit',
																		 'update'  => 'usuario.perfil.update',
																		 'show'    => 'usuario.perfil.show',
																		 'store'   => 'usuario.perfil.store',
																		 'destroy' => 'usuario.perfil.destroy'
																		],
																		'except' => ['index']

																	  ]);

Route::resource('usuario/profesional','ProfesionalController',['names' => 
																		[
																		 'create'  => 'usuario.profesional.create',
																		 'edit'    => 'usuario.profesional.edit',
																		 'update'  => 'usuario.profesional.update',
																		 'show'    => 'usuario.profesional.show',
																		 'store'   => 'usuario.profesional.store',
																		 'destroy' => 'usuario.profesional.destroy'
																		],
																		'except' => ['index']

																	  ]);

Route::resource('profesional/profesion','ProfesionController',['names' => 
																		[
																		 'create'  => 'profesional.profesion.create',
																		 'edit'    => 'profesional.profesion.edit',
																		 'update'  => 'profesional.profesion.update',
																		 'show'    => 'profesional.profesion.show',
																		 'store'   => 'profesional.profesion.store',
																		 'destroy' => 'profesional.profesion.destroy',
																		 'index'   => 'profesional.profesion.index'
																		],
																	
																	  ]);

Route::get('profesional/profesion/{profesion}/servicio/create','ServicioController@ServicioProfesionDeterminada')->name('profesion.servicio.create');
//Route::post('profesional/{profesional}/profesion/{profesion}/servicio','ServicioController@store')->name('profesion.servicio.store');

Route::resource('profesional/servicio','ServicioController',['names' => 
																		[
																		 'create'  => 'servicio.create',
																		 'edit'    => 'servicio.edit',
																		 'update'  => 'servicio.update',
																		 'show'    => 'servicio.show',
																		 'store'   => 'servicio.store',
																		 'destroy' => 'servicio.destroy',
																		 'index'   => 'servicio.index'
																		],
																	
																	  ]);





Route::get('ajax-sub-categoria/{sub_categoria_id?}','CategoriaController@profesionalesTipoCategoria')
																->name('sub.categoria.elegir.profesion');

Route::resource('categorias','CategoriaController');

Route::get('contratacion/profesional/{profesional}/perfil','ContratacionController@datosProfesional')
																->name('contatacion.profesional.perfil');


Route::get('contatacion/servicio/{servicio}/ver','ContratacionController@index')
																->name('contratacion.index');
																
Route::get('contatacion/servicio/{servicio}','ContratacionController@show')
																->name('contratacion.show');


Route::resource('contatacion/servicio/{servicio}','ContratacionController',['names' => 
																		[

																		 'create'  => 'contratacion.create',
																		 'store'  => 'contratacion.store'
																	
																		],
																		'only' => ['create','store'],
																		'except' => 'index'
																	
																	  ]);

Route::get('contratacion/servicio','ContratacionController@listado_contratacion')->name('contratacion.listado');


Route::get('contratacion/servicio/{servicio}/aceptar','ContratacionController@aceptar')->name('contratacion.aceptar');
Route::get('contratacion/servicio/{servicio}/cancelar','ContratacionController@cancelar')->name('contratacion.cancelar');


Route::get('contratacion/servicio/data/{estado}/ajax','ContratacionController@datos_listado_ajax')->name('contratacion.listado.ajax');

Route::post('comentario/nuevo/{servicio}','ComentarioController@ajax_store')->name('comentario.nuevo');
Route::get('contratacion/servicio/comentario/like/{servicio}','ComentarioController@like')->name('comentario.like');
Route::get('contratacion/servicio/comentario/dislike/{servicio}','ComentarioController@dislike')->name('comentario.dislike');


Route::get('contratacion/ajax/{servicio}','ComentarioController@CantidadComentarios')->name('comentario.cantidad');

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;

use App\User as Usuario;
use Auth;


class UsuarioController extends Controller
{
    
    public function datosUsuarios()
    {
                
        $usuario=Auth::user();
        $read=true;
        return view('usuario.index',compact('usuario','read'));

    }
    

    public function datosUsuariosEdit()
    {
                
        $usuario=Auth::user();
        return view('usuario.formulario.datos_usuario',compact('usuario'));

    }

    public function datosUsuariosUpdate(Request $rqt)
    {
                
        $usuario=Auth::user();
        $usuario->update($rqt->all());
        
        if (isset($usuario->perfil_usuario)) {
             $usuario->perfil_usuario()->update($rqt->only(
                                                            'nombre_completo',
                                                            'telefono',
                                                            'domicilio'
                                                        ));
        }

        if (isset($usuario->profesional)) {
               $usuario->profesional()->update($rqt->only(
                                                                'cuil',
                                                                'telefono_alternativo'
                                                             ));
        }
       
        return redirect()->route('usuario.datos');

    }

    public function show($id)
    {
    	$usuario=Auth::user();
        $read=true;
        return view('usuario.formulario.show',compact('usuario','read'));
    }

    public function edit($id)
    {
        
        $usuario=Auth::user();

        return view('usuario.formulario.edit',compact('usuario'));

    }

    public function update($id,Request $rqt)
    {
        
        $usuario=Auth::user()->update($rqt->all());	
        return redirect()->route('usuario.datos');
    }

  

    public function destroy($id){
        Auth::user()->baja();
    }


}

resources/views/usuario/formulario/datos_usuario.blade.php
@extends('layouts.template')

@section('htmlheader_title')
    Usuario|Datos
@endsection


@section('contentheader_title')
   <i class="fa fa-street-view fa-fw w3-margin-right w3-large w3-text-teal"></i> Usuario: {{$usuario->nick}}
@endsection

@section('contentheader_description') 
    datos 
@endsection
       



@section('main-content')


    {!! Form::model($usuario,['method' => 'PUT','route'=>['usuario.datos.update',$usuario->id],'id'=>'usuario']) !!}


 <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
            <li class="">
                <a aria-expanded="false" href="#tab_1" data-toggle="tab"><i class="fa fa-user fa-fw w3-margin-right w3-large w3-text-teal"></i>Datos Usuario</a>
            </li>


            <li class="">
                <a aria-expanded="false" href="#tab_2" data-toggle="tab"><i class="fa  fa-group fa-fw w3-margin-right w3-large w3-text-teal"></i>Datos Personales</a>
            </li>

            <li class="">
                <a aria-expanded="false" href="#tab_3" data-toggle="tab"><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Datos Laborales</a>
            </li>
           
        </ul>

        <div class="tab-content">
         <!-- tab-pane -->
            <div class="tab-pane active" id="tab_1">
                
                @include('usuario.partials.form')
                 <a href="{{route('usuario.show',$usuario->id)}}" class="btn btn-info">Ver</a>
                
            </div> <!-- /.tab-pane -->

              <!-- /.tab-pane -->
            <div class="tab-pane" id="tab_2">

                  @if(isset($usuario->perfil_usuario))
                     @include('perfil_usuario.partials.form')
                      <a href="{{route('usuario.perfil.show',[$usuario->id,$usuario->perfil_usuario->id])}}" class="btn btn-info">Ver</a>  
                  @else

                    <a href="{{ route('usuario.perfil.create',$usuario->id) }}" class="btn btn-success">Agregar</a>
                    <br><br>

                     <p><i class="fa fa-exclamation-circle fa-fw w3-margin-right w3-large w3-text-teal"></i>no tiene un perfil registrado</p>


             
                @endif

                 

              
            </div>
              <!-- /.tab-pane -->
            <div class="tab-pane" id="tab_3">


                @if(isset($usuario->profesional))
                  
                 @include('profesional.partials.form')
                  <a href="{{route('usuario.profesional.show',[$usuario->id,$usuario->profesional->id])}}" class="btn btn-info">Ver</a> 
                @else
                 <a href="{{ route('usuario.profesional.create',$usuario->id) }}" class="btn btn-success">Agregar</a>
                 <br><br>

                  <p><i class="fa fa-exclamation-circle fa-fw w3-margin-right w3-large w3-text-teal"></i>no esta registrado como profesional</p>

  
                  @endif


            </div>
            
        </div>
            <!-- /.tab-content -->

        <div class="box-footer">
        
       
          

                {!! Form::submit('Guardar', ['class' => 'btn btn-success ','id' => 'guardar']) !!}
           

                <a href="{{ route('usuario.datos') }}" class="btn btn-danger btn">volver</a>

     

         </div>

    </div>
          <!-- nav-tabs-custom -->

   

     {!! Form::close() !!}

      
 


@endsection

resources/views/usuario/formulario/edit.blade.php
@extends('layouts.template')

@section('htmlheader_title')
    Usuario|Ver
@endsection


@section('contentheader_title')
   Usuario: {{$usuario->nick}}
@endsection

@section('contentheader_description') 
    datos 
@endsection
       



@section('main-content')

 {!! Form::model($usuario,['method' => 'PUT','route'=>['usuario.update',$usuario->id],'id'=>'usuario']) !!}

	<div class="nav-tabs-custom">
		<ul class="nav nav-tabs">
            <li class="active">
                <a aria-expanded="false" href="#tab_1" data-toggle="tab">Datos Usuario</a>
            </li>
        </ul>
		<div class="tab-content">

   
        	@include('usuario.partials.form')
        
 

 		</div>


    	<div class="box-footer">
        
     		 
                {!! Form::submit('Guardar', ['class' => 'btn btn-success ','id' => 'guardar']) !!}
                <a href="{{ route('usuario.datos' ) }}" class="btn btn-danger btn">volver</a>         

                <a href="{{route('usuario.show',$usuario->id)}}" class="btn btn-info">Ver</a>


            

         </div>


    </div>
             
   {!! Form::close() !!}

@endsection

resources/views/usuario/formulario/show.blade.php
@extends('layouts.template')

@section('htmlheader_title')
    Usuario|Ver
@endsection


@section('contentheader_title')
   Usuario: {{$usuario->nick}}
@endsection

@section('contentheader_description') 
    datos 
@endsection
       



@section('main-content')


	<div class="nav-tabs-custom">
		<ul class="nav nav-tabs">
            <li class="active">
                <a aria-expanded="false" href="#tab_1" data-toggle="tab">Datos Usuario</a>
            </li>
        </ul>
		<div class="tab-content">
    		@include('usuario.partials.form')
    	</div>


    	<div class="box-footer">
        
     		 @if(!(isset($read)))
                {!! Form::submit('Guardar', ['class' => 'btn btn-success ','id' => 'guardar']) !!}
                 <a href="{{ url('/') }}" class="btn btn-danger btn">cancelar</a>
            @else

                <a href="{{route('usuario.edit',$usuario->id)}}" class="btn btn-warning ">Editar</a>

                 <a href="{{ route('usuario.datos' ) }}" class="btn btn-danger btn">volver</a>

            @endif
            

         </div>


    </div>
             


@endsection